name=DCCInterfaceMaster-TMC
version=7.0.0
author=Wolfgang Kufer, Don Goodman, Philipp Gahtow, Aiko Pras, Rob van Hoeijen
maintainer=Twentse Modelspoorweg Club (TMC)
sentence=NMRA / RCN DCC packet transmission
paragraph=This library allows the generation of jitter free DCC signals on modern processors (RP2040 / STM32 / ESP32 / DxCore / ...).
category=Communication
url=
architectures=*
